version: "3.8"

services:
  authorization-server:
    build:
      context: ./packages/authorization-server
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
      - "9230:9229"
    environment:
      NODE_ENV: development
      PORT: 8000
      DEBUG_PORT: 9229
      HOST: localhost
      PROTOCOL: https
      CERT: certificate.crt
      KEY: private.key
      DB_HOST: authorization-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: authorization-db
    depends_on:
      - authorization-db

  authorization-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authorization-db
    volumes:
      - authorization_data:/var/lib/postgresql/data

  resource-server:
    build:
      context: ./packages/resource-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9229:9229"
    environment:
      NODE_ENV: development
      PORT: 8000
      DEBUG_PORT: 9229
      HOST: localhost
      PROTOCOL: https
      CERT: certificate.crt
      KEY: private.key
      DB_HOST: resource-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: resource-db
    depends_on:
      - resource-db

  resource-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resource-db
    volumes:
      - resource_data:/var/lib/postgresql/data

volumes:
  resource_data:
  authorization_data:
